### ISSUE TITLE
Fix mismatch in genesis in Evochain

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos-evolution-node#32]
- [x] #36 
- [x] #35 
- [x] #34

**Comment by tonimateos** [comment]
**ACCEPTANCE**:

The nodes in dev branch sync from genesis without issues

**Comment by asiniscalchi** [comment]
https://github.com/freeverseio/laos-evolution-node/pull/35 
just make the chain_spec raw

**Comment by asiniscalchi** [comment]
https://github.com/freeverseio/laos-evolution-node/pull/34
refactor the helmfile

**Comment by asiniscalchi** [comment]
https://github.com/freeverseio/laos-evolution-node/pull/36
